[package]
name = "danse"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.5.0", features = ["full"] }
trust-dns-proto = "0.20.2"
reqwest = "0.11.3"